# Generated by Django 5.1.3 on 2025-02-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_exerciselist_exercise_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="personal_records",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="exerciselist",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("Dumbbell Exercises", "Dumbbell Exercises"),
                    ("Barbell Exercises", "Barbell Exercises"),
                    ("Machine-Based Workouts", "Machine-Based Workouts"),
                    ("Bodyweight Training", "Bodyweight Training"),
                    ("Kettlebell Workouts", "Kettlebell Workouts"),
                    ("Resistance Band Training", "Resistance Band Training"),
                    ("Cable Exercises", "Cable Exercises"),
                    ("Cardiovascular Exercise", "Cardiovascular Exercise"),
                    ("Yoga and Flexibility Workouts", "Yoga and Flexibility Workouts"),
                ],
                default="Dumbbell Exercises",
                max_length=100,
            ),
        ),
    ]
