# Generated by Django 5.1.3 on 2025-02-19 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_user_personal_records_and_more"),
        ("api", "xxxx_initialize_personal_records"),
    ]

    operations = []
